### ISSUE TITLE
Funkiness when "text=auto" is in .gitattributes

### ISSUE THREAD

**Issue by matro** [buildinspace/peru#122]
I think I found an interesting edge-case kind of thing here... not sure if it's a problem that Peru can solve for itself, or if it's a weird Git thing.

If a Git repo is set to normalize line-endings (`core.autocrlf` in Git's config.), Peru thinks thinks "Imported files have been modified" if line-endings differ between files in Peru's cache and the repo's working directory.

To reproduce:

 1. Have a Git repo with these in it:
    - a `peru.yaml` file with one or more modules have contents with different line-ending characters.
    - a `.gitattributes` file with [`* text=auto`](https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings) and/or [a matching global git config](https://help.github.com/articles/dealing-with-line-endings/#global-settings-for-line-endings).
 1. Run `peru sync`.

Expected:

 * Peru does what Peru does, dependences are populated in the working directory, and there is much rejoicing.

Actual:

 * If `peru sync` had already been run, Peru warns that "Imports would overwrite preexisting files (use --force to write anyway):" and lists the files it thinks are different.
 * Running `peru sync --force` (or just `peru sync` on a clean tree) prints this traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/peru", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/peru/main.py", line 308, in main
    async.run_task(command_fn(params))
  File "/usr/local/lib/python3.4/site-packages/peru/async.py", line 25, in run_task
    return asyncio.get_event_loop().run_until_complete(coro)
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/base_events.py", line 316, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.4.3_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.4/site-packages/peru/main.py", line 88, in do_sync
    params.runtime, params.scope, params.imports, params.runtime.sync_dir)
  File "/usr/local/lib/python3.4/site-packages/peru/imports.py", line 14, in checkout
    force=runtime.force)
  File "/usr/local/lib/python3.4/site-packages/peru/cache.py", line 164, in export_tree
    self._git('checkout-index', '--all', work_tree=dest)
  File "/usr/local/lib/python3.4/site-packages/peru/cache.py", line 75, in _git
    raise self.GitError(command, output, process.returncode)
peru.cache.GitError: git command "git --git-dir=<working-dir>.peru/cache/trees --work-tree=<working-dir> checkout-index --all" returned error code 128:
<filename1> already exists, no checkout
<filename2> already exists, no checkout
<filename3> already exists, no checkout
...
<filenameN> already exists, no checkout
```

Other bits:

 * All of this goes away and Peru runs normally when the `core.autocrlf` setting is completely unset.
 * This also happens with `peru reup`, both the safe-fail because of perceived changes in the working dir, and the traceback when running with `--force`.

I was able to confirm that it's line-ending shenanigans that's getting Peru's Git guts tripped up. Despite the errors in the traceback, it looks like Peru is still getting files written out to the file system correctly. I _think_. Using Git to track the imported files themselves, the only changes to these files that Git sees are line-endings; do a `git stash && git stash pop` and the working directory will be clean again. Or, if doing a `peru reup --force`, the list of changed files will drop from "lots and lots" to only `peru.yaml` and whatever few files have changed between the two `rev`s.

**Comment by matro** [comment]
When I added `--force` to the `git-checkout-index` command in cache.py (line 164), this problem also went away... but from my limited understanding of the code, I've a strong feeling that this is a terrible, horrible idea.

Not sure what else to suggest or how to work around this... but it seems like Peru's Git-guts are at the mercy of the user's global Git config and the whims of a repo's `.gitattributes`. I can either give up on normalizing line-endings, or have Peru make noise that sounds like it's not working (even though it seems to ultimately work fine).

Maybe a `.gitattributes` inside `.peru/` to insulate its private world from the host repo & global git configs? Not sure from https://git-scm.com/docs/gitattributes if it is possible.

**Comment by oconnor663** [comment]
Ugh, `autocrlf` has bitten me before. I remember on another project some flavor of that setting made it so that `git status` was always dirty even after `git reset --hard` :p

In this case, I think you're right. Our git calls are respecting your projects `.gitattributes` when they shouldn't be. We override `$HOME` to disable your global `.gitconfig`, so hopefully there's a similar hack we can add for this file. Awesome bug find. Let me know if you have a git project I can clone to repro exactly what you're seeing.

(A little clarification for future reference. One of tricky things about peru's internals is that there are two very different ways we use git. One is the totally-internal-implementation-detail of moving file trees around and dumping them in your project, the *tree cache*. The other is the kind-of-exposed-to-users role of cloning remote git repos, the *git plugin*. Global configuration is only suppressed for the tree cache, because the git plugin might need things like your SSH keys and proxy settings.)

**Comment by oconnor663** [comment]
> When I added `--force` to the `git-checkout-index` command in cache.py (line 164), this problem also went away... but from my limited understanding of the code, I've a strong feeling that this is a terrible, horrible idea.

Yeah, `cache.py` is easily the trickiest area of the code, and it relies on the exact behavior of git's plumbing commands. The test coverage is decent, though, so if tests are passing there's a good chance nothing is broken :) I think in this case your change might be ok. It's very important that `export_tree` never overwrites files it didn't create without `force=True`, but here it's already aborting on lines 149 or 160. I don't think this would be the *best* fix though, because there might be other calls affected by `autocrlf` that we haven't stumbled on yet, and also other troublesome settings that can show up in `.gitattributes`. I'm still googling.

**Comment by oconnor663** [comment]
According to [the git docs](https://git-scm.com/docs/gitattributes), `$GIT_DIR/info/attributes` has highest precedence of all the various attributes files. In this case `$GIT_DIR` is going to be `.peru/cache/trees`, so we definitely could create that file. Unfortunately it looks like we need to explicitly name each attribute we want to override -- annoying but not the end of the world.

**Comment by oconnor663** [comment]
@matro I am able to repro your bug (woo!), but I'm *not* able to repro it with just `~/.gitconfig`. I'm only able to repro with `.gitattributes` in my peru project. Your wrote above that you were able to repro it both ways. Are you sure? If so, could you link me to the repos you're using?

**Comment by oconnor663** [comment]
Hmm, so far that fix I had in mind isn't working. It doesn't override what's in the project for some reason.

**Comment by oconnor663** [comment]
Ok, I think this is fixed. @matro, can you confirm. Also, can you tell me what sort of project was setting this arcane property? :-D

**Comment by matro** [comment]
I did some testing, and I'm still seeing the same behavior... but I'm also pretty convinced there are other oddities in my local environments in play as well. I haven't been able to test on a clean box yet, either. Only so much any tool can be expected to do when the world it's working in is wonky.

This is also making me consider dropping this property from our `.gitattributes`. Most of our troubles have been in repositories where we're "doing it wrong" and not git-ignoring things that Peru imports anyways... so if I can get us to make those repos unsucky, many problems will go away.

**Comment by matro** [comment]
If I come across this problem again, I'll get better test info before bringing this up again. Thanks for the fix!

**Comment by oconnor663** [comment]
Apologies, I haven't actually *released* a new version of peru with this fix yet. Are you sure you were testing from master?
